### PR TITLE
Streaming API

### PR DESCRIPTION
**Pull request by swizzard**

### CODE REVIEW

**Comment by swizzard** [comment]
@syucream I'm not sure why travis failed--I just ran the same commands on my machine and everything compiled correctly.

**Comment by syucream** [comment]
@swizzard hmm, ok I'll check the CI job. 👀

**Comment by as-capabl** [comment]
It seems that `ghc-8.0.1` or newer is required.

The `Conduit` module was added at `conduit-1.3.0`. `conduit-1.3.0` requires `base-4.9.0.0` or newer. `base-4.9.0.0` corresponds to GHC version 8.0.1 (according to https://wiki.haskell.org/Base_package).

**Comment by as-capabl** [comment]
It's better to update package constraints as following;

```
  Build-Depends: base >= 4.9 && < 5,
     ...
                 conduit >= 1.3.0,
```

**Comment by swizzard** [comment]
@as-capabl I tried updating the constraints as you recommended; it looks like we got farther but not far enough. 

Is there a way we could switch to using `stack` instead of `cabal` in travis? @syucream

**Comment by as-capabl** [comment]
@swizzard  I agree that we got farther.  Because the ghc version is constrained by the travis configuration, some modification of it is needed anyway.
Using `stack` is good idea if possible.

**Comment by syucream** [comment]
@swizzard I migrated from cabal to stack. Can you merge `master` and push this branch?

**Comment by syucream** [comment]
And can you bump up version to `0.4.0` ?  🙏

**Comment by swizzard** [comment]
travis is green :raised_hands: @syucream

**Comment by syucream** [comment]
@swizzard great! This PR looks good!

**Review by syucream — APPROVED** [review]

**Comment by syucream** [comment]
Finally I've uploaded `0.4.0` to Hackage. https://hackage.haskell.org/package/Hastodon-0.4.0
Thank you for your cooperation, @swizzard @as-capabl 😃

**Comment by swizzard** [comment]
:tada:

**Pull request merged**
