### PR TITLE
use String instead of Int in API functions

### LINKED ISSUE #24: Weirdness in types
Hi,

Just noticed something a bit strange, HastodonId is a string in Types but functions that takes an Id want an Int. Having to convert an Id from String to Int to pass to to the library that will in turn turn it to String seems a bit silly to me. Didn't use to be a problem in the older Hastodon versions, so I assume that's just because of the change in the Mastodon API moving the Id from Int to String. Shouldn't all functions now be taking Strings instead ?

### PR DESCRIPTION
**Pull request by swizzard**
fixes https://github.com/syucream/hastodon/issues/24

### CODE REVIEW

**Comment by as-capabl** [comment]
@swizzard
In my understanding, account-ids and status-ids are expressed by `HastodonId` defined at Type.hs.
Would you use `HastodonId` instead of `String`?

**Comment by as-capabl** [comment]
And I noticed several points that needed to change type into `HastodonId` in addition;

- Types.hs: statusInReplyToId, statusInReplyToAccountId https://github.com/syucream/hastodon/blob/334b19d6d03d25f90c095304a482af8bb22dce62/Web/Hastodon/Types.hs#L230-L231
- Option.hs: inReplyToId, mediaIds https://github.com/syucream/hastodon/blob/334b19d6d03d25f90c095304a482af8bb22dce62/Web/Hastodon/Option.hs#L283-L287

**Comment by swizzard** [comment]
@as-capabl done. i'm a little uncomfortable having account ids and status ids and media ids all be `HastodonId`s, since they represent pretty different things, but that can be put off for another commit. Similarly, it may be worth newtyping ids to prevent them from getting mixed up with other strings like status content

**Comment by as-capabl** [comment]
@swizzard Thanks a lot! :+1: I agree that various ids should be expressed by distinct types.

**Comment by swizzard** [comment]
closed in favor of https://github.com/syucream/hastodon/pull/27

**Pull request closed without merging**
