### PR TITLE
Added media upload and media status capabilities

### PR DESCRIPTION
**Pull request by william42**
I created functions to allow posting toots with media.  Right now, it only allows for upload from file because a MIME type is necessary and deriving one from the filename is the easiest option for my uses.  I also created a function to toot with media IDs.

### CODE REVIEW

**Comment by william42** [comment]
Oops; I forgot to add `mime-types` and `http-client` dependencies in the cabal file.

**Comment by syucream** [comment]
@william42 Cool! 😍  Can you update implemented methods list on README?
https://github.com/syucream/hastodon/blob/master/README.md

**Comment by william42** [comment]
Implemented methods list updated. (As well as my own name on the contributors list)

**Comment by syucream** [comment]
Nice work! Merged. :)

**Comment by syucream** [comment]
I've just published `0.3.1` to Hackage.
https://hackage.haskell.org/package/Hastodon

**Pull request merged**
